engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
  fixme:
    enabled: true
plugins:
  eslint:
    enabled: true
    channel: 'eslint-6'
    config:
      config: .eslintrc.yml
    checks: 
      array-bracket-newline:
        enabled: false
      complexity:
        enabled: true
      for-direction:
        enabled: false
      func-style:
        enabled: false
      global-require:
        enabled: false
      no-buffer-constructor:
        enabled: false
      no-undef:
        enabled: false
      object-curly-spacing:
        enabled: false
      padding-line-between-statements:
        enabled: false
      semi-style:
        enabled: false
      switch-colon-spacing:
        enabled: false
      spaced-comment:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.ts"
exclude_paths:
- config/
- dist/
- app/unused/**/*
- public/**/*